### ISSUE TITLE
How to extract target to a PDF.lnk and replace target to new location?

### ISSUE THREAD

**Issue by ZakNazif** [mbrowniebytes/powershell-copy-shortcut-contents#2]
I have modified your great scipt to meet my needs as follows, however, I am unable to extract the target for a PDF.lnk file and change the terget to a new location

`#https://github.com/mbrowniebytes/powershell-copy-shortcut-contents/blob/master/_copy_shortcut_contents.ps1

# zShortcuts Extract with Robocopy 1.ps1
# from the source directory, find all shortcuts, and copy the shortcut contents to a destination directory

#Set-ExecutionPolicy -ExecutionPolicy RemoteSigned

# options 

# only output what would happen, dont actually copy anything
$dryrun = 0;

# where to copy from; full path; end with slash
# use current dir as srcDir
#$srcDir = (Get-Item -Path ".\" -Verbose).FullName + "\"
$srcDir = "C:\zSOURCE\"

# where to copy to; full path; end with slash
# $destDir = "T:\"
$destDir = "C:\zDESTINATION\"

# where to copy the Shortcuts; full path; end with slash
$scDir = "$destDir\zShortcuts\"

# where to copy the Shortcuts; full path; end with slash
$SLog = "C:\Users\Zakaria.Nazif\OneDrive - Worley\Zzz\Misc\WindowsPowerShell\"

# 1 (recommended) - use dos copy to get progress per file, 0 - use copy-item 
$useCopyProgress = 1;

# if dest path exists, skip
$skipExistingDestPath = 0;

# 1 (recommended) - if dest file exists, skip, 0 - re-copy
$skipExistingDestFile = 1;

# 1 - show existing files, 0 - dont show, reducing output
$showExistingFiles = 0;

# start

C:\Windows\System32\robocopy.exe $srcDir $destDir /mir /e /fp /log+:"$SLog\zRobocopyFolders.txt"

if ($scDir -eq "") {
	write-host "Stopped"
	write-host "Edit srcDir and destDir and $scDir variables and read script"
	write-host "Press any key to continue..."
	[void][System.Console]::ReadKey($true)
	exit
}

# Get all shortcuts
$shortcuts = gci $destDir -s -Include '*.lnk' | where {$_.PSIsContainer -eq $false}

# iterate over shortcuts
$total = $shortcuts.count
$index = 0
$sh = New-Object -ComObject WScript.Shell

foreach ($shortcut in $shortcuts) {
	# get target path from shortcut ie what shortcut points to	
	$srcPath = $sh.CreateShortcut($shortcut.fullname).Targetpath
	$srcDrive = $srcPath.substring(0, 3)

	# duplicate src folder structure in dest
	$destPath = $srcPath.replace($srcDrive, $scDir)

Write-Host "shortcut  " $shortcut -ForegroundColor yellow
Write-Host "srcPath  " $srcPath -ForegroundColor green
Write-Host "srcDrive  " $srcDrive -ForegroundColor blue
Write-Host "destPath  " $destPath.fullname -ForegroundColor DarkMagenta

	# skip existing dirs
	if (Test-Path "$destPath") {
		if ($skipExistingDestPath) {
			continue
		}
	}

	# get dest path for copy-item to recurse into	
	if (Test-Path "$destPath") {
		# if path exists, copy-item will re-create within it, so go up one level
		$destRecreatePath = "$destPath\..\"	
	} else {
		# if path does not exist, copy-item will create it
		$destRecreatePath = $destPath
	        }	
	
	# copy shortcut contents to destination, including subdirs
    # ! means "NOT"
	if (!$useCopyProgress) {
		# use copy-item to copy shortcut contents to destination, including subdirs
		# but no progress per file
		if ($dryrun) {
            write-host "dryrun: C:\Windows\System32\robocopy.exe $srcPath $destRecreatePath /mir /e /fp /log+:"$SLog\zRobocopyFolders.txt""
		} else {
			# get current list of files, if any
			$exclude = ""
			if (Test-Path "$destPath") {
				$origFiles = gci "$destPath" -File -Recurse
				
				# exclude already copied dirs/files
				if ($skipExistingDestFile) {
					$exclude = gci $destPath
				                           }
                                       }
else {
				$origFiles = @()
	}

			# copy
			C:\Windows\System32\robocopy.exe $srcPath $destRecreatePath /mir /e /fp /log+:"$SLog\zRobocopyFolders.txt"

			# show results in destPath, from current or prior copy-item
			$files = gci "$destPath" -File -Recurse
			foreach ($file in $files) {			
				$srcFile = $file.fullname
				$destFile = $srcFile.replace($srcDrive, $scDir)
				$destRelPath = $destFile.replace($destPath, "")

            write-host $destFile
            Write-Host $file -ForegroundColor green

				if ($origFiles.fullname -contains $file.fullname) {
					if ($showExistingFiles) {
					}
				} else {
				}
			}			
		}
		
} else {			
		
		# copy folder structure only ie create srcPath directories in destRecreatePath
		if ($dryrun) {
            write-host "dryrun: C:\Windows\System32\robocopy.exe $srcPath $destRecreatePath /mir /e /fp /log+:"$SLog\zRobocopyFolders.txt""
		} else {		
			C:\Windows\System32\robocopy.exe $srcPath $destRecreatePath /mir /e /fp /log+:"$SLog\zRobocopyFolders.txt"
		}

		# copy files with progress
		$files = gci "$srcPath" -File -Recurse
		foreach ($file in $files) {
			$srcFile = $file.fullname
			$destFile = $srcFile.replace($srcDrive, $scDir)
			
			# skip existing files, compare by date
			if (Test-Path "$destFile") {
				$srcLastTime = $file.LastWriteTime				
				$destLastTime = (gci "$destFile").LastWriteTime
				if ($srcLastTime -eq $destLastTime) {
					if ($showExistingFiles) {
					}						
					if ($skipExistingDestFile) {
						continue
					}
				}
			}		
			
			# show file name being copied

			if ($dryrun) {
				write-host ""
				write-host "dryrun: C:\Windows\System32\robocopy.exe $srcPath $destRecreatePath /mir /e /fp /log+:"$SLog\zRobocopyFolders.txt""
			} else {
				# https://stackoverflow.com/questions/2434133/progress-during-large-file-copy-copy-item-write-progress
			    C:\Windows\System32\robocopy.exe $srcPath $destRecreatePath /mir /e /fp /log+:"$SLog\zRobocopyFolders.txt"
			}
		}		
	}

    #write-host $shortcut -ForegroundColor yellow
    $link = $sh.CreateShortcut($shortcut)
	$link.TargetPath = $destRecreatePath
    $link.WorkingDirectory = $destRecreatePath

Write-Host "link  " $link -ForegroundColor yellow
Write-Host "WorkingDirectory  " $link.WorkingDirectory -ForegroundColor Gray
Write-Host "TargetPath  " $link.TargetPath -ForegroundColor red

	$link.Save()
}

# finish
write-host ""
write-host "Finished"
write-host "Press any key to continue..."
[void][System.Console]::ReadKey($true)`

**Comment by mbrowniebytes** [comment]
closing, shortcuts (lnk) are copied to dest independent of content type
